name: Quality Check

on:
  pull_request:
    branches:
      - main
jobs:
  quality:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Code
       uses: actions/checkout@v5

     - name: Setup Node
       uses: actions/setup-node@v5
       with:
        node-version: 24
        cache: npm

     - name: Install Packages
       run: npm install

     - name: Run Lint
       run: npm run lint